version: '3.4'

services:
    catalogdb:
        container_name: catalogdb
        restart: always
        volumes:
        - ${WEBAPP_STORAGE_HOME}/site:/data/db
        ports:
        -   "27017:27017"  
    catalogapi:
        container_name: catalogapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "CatalogDatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
        depends_on:
            - catalogdb
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersevrets
            - ${HOME}/.asnet/https:/root/.aspnet/https
        ports:
        - "8000:80"
